### ISSUE TITLE
[Feature Request] Add disconnect

### ISSUE THREAD

**Issue by madhat2r** [cdown/btmenu#1]
It would be nice if you could also disconnect devices. Perhaps when you select a device, if it is already connected, it would disconnect.

Thanks for this script, it is very handy!

**Comment by cdown** [comment]
Hey! You can do this with `btmenu -d` :-)

https://github.com/cdown/btmenu/blob/master/btmenu#L91

**Comment by madhat2r** [comment]
Sweet! Did not notice that. Thanks!

**Comment by cdown** [comment]
No worries! btmenu is still pretty rough around the edges, but it mostly works.
